// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const COURSE_SCHEMA = "course_test";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    headers.set("Accept-Profile", COURSE_SCHEMA);
    headers.set("Content-Profile", COURSE_SCHEMA);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseAdminClient() {
  // On Cloudflare Workers (Nitro's cloudflare-module preset), the platform
  // bindings aren't reliably reflected in `process.env` inside this app's
  // request pipeline. Nitro DOES guarantee `globalThis.__env__` is set to the
  // Worker's `env` object on every single request (see
  // nitro/presets/cloudflare/runtime/_module-handler.mjs), so use that as the
  // primary source for anything not safe to build-time-inline.
  const cfEnv = (globalThis as { __env__?: Record<string, string | undefined> }).__env__;

  // The URL isn't sensitive, so it's safe to fall back to the Vite build-time
  // constant when neither runtime source has it. The service role key must
  // never be build-time-inlined (that would ship it to the browser bundle),
  // so it only ever comes from a genuine runtime binding.
  const SUPABASE_URL =
    cfEnv?.SUPABASE_URL || import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_SERVICE_ROLE_KEY =
    cfEnv?.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;

  // TEMPORARY DIAGNOSTIC — safe to leave logged briefly, never prints values,
  // only whether each source exists and which keys it has. Remove once the
  // env-binding issue is confirmed fixed.
  console.error(
    "[Supabase][diag]",
    JSON.stringify({
      hasGlobalEnv: typeof globalThis !== "undefined" && "__env__" in globalThis,
      globalEnvKeys: cfEnv ? Object.keys(cfEnv) : null,
      hasProcessEnv: typeof process !== "undefined" && !!process.env,
      processEnvKeys: typeof process !== "undefined" && process.env ? Object.keys(process.env) : null,
      hasViteUrl: !!import.meta.env.VITE_SUPABASE_URL,
    }),
  );

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_SERVICE_ROLE_KEY ? ["SUPABASE_SERVICE_ROLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Configure them in Cloudflare.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
    },
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});