CREATE TABLE IF NOT EXISTS public.email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template_key TEXT NOT NULL UNIQUE,
  name_fi TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_sv TEXT NOT NULL,
  subject_fi TEXT NOT NULL,
  subject_en TEXT NOT NULL,
  subject_sv TEXT NOT NULL,
  body_fi TEXT NOT NULL,
  body_en TEXT NOT NULL,
  body_sv TEXT NOT NULL,
  description_fi TEXT,
  description_en TEXT,
  description_sv TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by UUID REFERENCES public.profiles(id)
);

GRANT SELECT ON public.email_templates TO authenticated;
GRANT ALL ON public.email_templates TO service_role;

ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Super admin can manage email templates"
  ON public.email_templates FOR ALL TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'));

CREATE POLICY "Authenticated users can read email templates"
  ON public.email_templates FOR SELECT TO authenticated
  USING (true);

CREATE TRIGGER email_templates_touch_updated_at
  BEFORE UPDATE ON public.email_templates
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

INSERT INTO public.email_templates (template_key, name_fi, name_en, name_sv, subject_fi, subject_en, subject_sv, body_fi, body_en, body_sv, description_fi, description_en, description_sv) VALUES
('welcome',
 'Tervetuloa-viesti', 'Welcome Email', 'Välkomstmeddelande',
 'Tervetuloa Vahvuusseikkailuun!', 'Welcome to Strength Adventure!', 'Välkommen till Styrkeäventyret!',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Vahvuusseikkailu</h1><p style="color: rgba(255,255,255,0.8); margin: 8px 0 0;">Huomaa hyvä!</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Tervetuloa, {{name}}!</h2><p>Tilisi on luotu onnistuneesti. Olet valmis aloittamaan vahvuusseikkailun!</p><a href="{{login_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Kirjaudu sisään</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Strength Adventure</h1><p style="color: rgba(255,255,255,0.8); margin: 8px 0 0;">See the Good!</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Welcome, {{name}}!</h2><p>Your account has been created successfully. You are ready to start your strength adventure!</p><a href="{{login_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Log in</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Styrkeäventyret</h1><p style="color: rgba(255,255,255,0.8); margin: 8px 0 0;">Se det goda!</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Välkommen, {{name}}!</h2><p>Ditt konto har skapats. Du är redo att börja ditt styrkeäventyr!</p><a href="{{login_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Logga in</a></div></div>',
 'Lähetetään kun uusi käyttäjä rekisteröityy', 'Sent when a new user registers', 'Skickas när en ny användare registrerar sig'),
('password_reset',
 'Salasanan palautus', 'Password Reset', 'Lösenordsåterställning',
 'Vaihda salasanasi — Vahvuusseikkailu', 'Reset your password — Strength Adventure', 'Återställ ditt lösenord — Styrkeäventyret',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Vahvuusseikkailu</h1></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Salasanan vaihto</h2><p>Pyysit salasanan vaihtoa. Klikkaa alla olevaa linkkiä vaihtaaksesi salasanasi.</p><a href="{{reset_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Vaihda salasana</a><p style="color: #888; font-size: 12px; margin-top: 16px;">Jos et pyytänyt tätä, voit jättää tämän viestin huomiotta.</p></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Strength Adventure</h1></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Password Reset</h2><p>You requested a password reset. Click the link below to set a new password.</p><a href="{{reset_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Reset Password</a><p style="color: #888; font-size: 12px; margin-top: 16px;">If you did not request this, you can ignore this email.</p></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Styrkeäventyret</h1></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h2 style="color: #3f276f;">Lösenordsåterställning</h2><p>Du begärde en lösenordsåterställning. Klicka på länken nedan.</p><a href="{{reset_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold;">Återställ lösenord</a><p style="color: #888; font-size: 12px; margin-top: 16px;">Om du inte begärde detta kan du ignorera detta meddelande.</p></div></div>',
 'Lähetetään kun käyttäjä pyytää salasanan vaihtoa', 'Sent when user requests password reset', 'Skickas när användaren begär lösenordsåterställning'),
('monthly_teacher_report',
 'Opettajan kuukausiraportti', 'Teacher Monthly Report', 'Lärarens månadsrapport',
 'Vahvuusseikkailu — Kuukausiraportti {{month}}', 'Strength Adventure — Monthly Report {{month}}', 'Styrkeäventyret — Månadsrapport {{month}}',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Kuukausiraportti</h1><p style="color: rgba(255,255,255,0.8);">{{teacher_name}}, tässä kuukautesi yhteenveto</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Top 5 vahvuudet ryhmässäsi</h3>{{top_strengths}}<h3 style="color: #3f276f; margin-top: 24px;">Aktiivisimmat opiskelijat</h3>{{active_students}}<h3 style="color: #3f276f; margin-top: 24px;">Yhteenveto</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Avaa kojelauta</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Monthly Report</h1><p style="color: rgba(255,255,255,0.8);">{{teacher_name}}, here is your monthly summary</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Top 5 strengths in your group</h3>{{top_strengths}}<h3 style="color: #3f276f; margin-top: 24px;">Most active students</h3>{{active_students}}<h3 style="color: #3f276f; margin-top: 24px;">Summary</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Open Dashboard</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Månadsrapport</h1><p style="color: rgba(255,255,255,0.8);">{{teacher_name}}, här är din månadssammanfattning</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Topp 5 styrkor i din grupp</h3>{{top_strengths}}<h3 style="color: #3f276f; margin-top: 24px;">Mest aktiva elever</h3>{{active_students}}<h3 style="color: #3f276f; margin-top: 24px;">Sammanfattning</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Öppna instrumentpanelen</a></div></div>',
 'Lähetetään opettajille joka kuukauden ensimmäisenä', 'Sent to teachers on 1st of each month', 'Skickas till lärare den 1:a varje månad'),
('monthly_principal_report',
 'Rehtorin kuukausiraportti', 'Principal Monthly Report', 'Rektorns månadsrapport',
 'Vahvuusseikkailu — Kuukausiraportti {{month}}', 'Strength Adventure — Monthly Report {{month}}', 'Styrkeäventyret — Månadsrapport {{month}}',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Kuukausiraportti</h1><p style="color: rgba(255,255,255,0.8);">{{school_name}} — {{month}}</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Top 5 vahvuudet koko koulussa</h3>{{top_strengths_school}}<h3 style="color: #3f276f; margin-top: 24px;">Top vahvuudet per luokka</h3>{{top_strengths_per_class}}<h3 style="color: #3f276f; margin-top: 24px;">Aktiivisin luokka</h3>{{most_active_class}}<h3 style="color: #3f276f; margin-top: 24px;">Koulun yhteenveto</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Avaa kojelauta</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Monthly Report</h1><p style="color: rgba(255,255,255,0.8);">{{school_name}} — {{month}}</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Top 5 strengths school-wide</h3>{{top_strengths_school}}<h3 style="color: #3f276f; margin-top: 24px;">Top strengths per class</h3>{{top_strengths_per_class}}<h3 style="color: #3f276f; margin-top: 24px;">Most active class</h3>{{most_active_class}}<h3 style="color: #3f276f; margin-top: 24px;">School summary</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Open Dashboard</a></div></div>',
 '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;"><div style="background: linear-gradient(135deg, #3f276f, #6544a0); padding: 24px; border-radius: 12px 12px 0 0; text-align: center;"><h1 style="color: white; margin: 0;">Månadsrapport</h1><p style="color: rgba(255,255,255,0.8);">{{school_name}} — {{month}}</p></div><div style="background: white; padding: 24px; border: 1px solid #e5e7eb; border-radius: 0 0 12px 12px;"><h3 style="color: #3f276f;">Topp 5 styrkor i hela skolan</h3>{{top_strengths_school}}<h3 style="color: #3f276f; margin-top: 24px;">Topp styrkor per klass</h3>{{top_strengths_per_class}}<h3 style="color: #3f276f; margin-top: 24px;">Mest aktiva klass</h3>{{most_active_class}}<h3 style="color: #3f276f; margin-top: 24px;">Skolsammanfattning</h3>{{summary}}<a href="{{dashboard_url}}" style="display: inline-block; background: #e97070; color: white; padding: 12px 24px; border-radius: 25px; text-decoration: none; font-weight: bold; margin-top: 16px;">Öppna instrumentpanelen</a></div></div>',
 'Lähetetään rehtorille joka kuukauden ensimmäisenä', 'Sent to principal on 1st of each month', 'Skickas till rektor den 1:a varje månad')
ON CONFLICT (template_key) DO NOTHING;