/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LarareRouteImport } from './routes/larare'
import { Route as JoinCommunityRouteImport } from './routes/join-community'
import { Route as GaMedIGemenskapenRouteImport } from './routes/ga-med-i-gemenskapen'
import { Route as AventyrRouteImport } from './routes/aventyr'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AventyrScreenRouteImport } from './routes/aventyr.$screen'
import { Route as AuthStudentRouteImport } from './routes/auth.student'
import { Route as AuthOpettajaRouteImport } from './routes/auth.opettaja'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AdventureScreenRouteImport } from './routes/adventure.$screen'
import { Route as AuthenticatedOpettajaRouteImport } from './routes/_authenticated/opettaja'
import { Route as AuthenticatedLiityYhteisoonRouteImport } from './routes/_authenticated/liity-yhteisoon'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSeikkailuRouteRouteImport } from './routes/_authenticated/seikkailu/route'
import { Route as AuthenticatedSeikkailuIndexRouteImport } from './routes/_authenticated/seikkailu/index'
import { Route as AuthenticatedSeikkailuScreenRouteImport } from './routes/_authenticated/seikkailu/$screen'
import { Route as AuthenticatedOpettajaOppilasUserIdRouteImport } from './routes/_authenticated/opettaja_.oppilas.$userId'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LarareRoute = LarareRouteImport.update({
  id: '/larare',
  path: '/larare',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCommunityRoute = JoinCommunityRouteImport.update({
  id: '/join-community',
  path: '/join-community',
  getParentRoute: () => rootRouteImport,
} as any)
const GaMedIGemenskapenRoute = GaMedIGemenskapenRouteImport.update({
  id: '/ga-med-i-gemenskapen',
  path: '/ga-med-i-gemenskapen',
  getParentRoute: () => rootRouteImport,
} as any)
const AventyrRoute = AventyrRouteImport.update({
  id: '/aventyr',
  path: '/aventyr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AventyrScreenRoute = AventyrScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => AventyrRoute,
} as any)
const AuthStudentRoute = AuthStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOpettajaRoute = AuthOpettajaRouteImport.update({
  id: '/opettaja',
  path: '/opettaja',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AdventureScreenRoute = AdventureScreenRouteImport.update({
  id: '/$screen',
  path: '/$screen',
  getParentRoute: () => AdventureRoute,
} as any)
const AuthenticatedOpettajaRoute = AuthenticatedOpettajaRouteImport.update({
  id: '/opettaja',
  path: '/opettaja',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiityYhteisoonRoute =
  AuthenticatedLiityYhteisoonRouteImport.update({
    id: '/liity-yhteisoon',
    path: '/liity-yhteisoon',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeikkailuRouteRoute =
  AuthenticatedSeikkailuRouteRouteImport.update({
    id: '/seikkailu',
    path: '/seikkailu',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSeikkailuIndexRoute =
  AuthenticatedSeikkailuIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSeikkailuRouteRoute,
  } as any)
const AuthenticatedSeikkailuScreenRoute =
  AuthenticatedSeikkailuScreenRouteImport.update({
    id: '/$screen',
    path: '/$screen',
    getParentRoute: () => AuthenticatedSeikkailuRouteRoute,
  } as any)
const AuthenticatedOpettajaOppilasUserIdRoute =
  AuthenticatedOpettajaOppilasUserIdRouteImport.update({
    id: '/opettaja_/oppilas/$userId',
    path: '/opettaja/oppilas/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/adventure': typeof AdventureRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/aventyr': typeof AventyrRouteWithChildren
  '/ga-med-i-gemenskapen': typeof GaMedIGemenskapenRoute
  '/join-community': typeof JoinCommunityRoute
  '/larare': typeof LarareRoute
  '/teacher': typeof TeacherRoute
  '/seikkailu': typeof AuthenticatedSeikkailuRouteRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/opettaja': typeof AuthenticatedOpettajaRoute
  '/adventure/$screen': typeof AdventureScreenRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/aventyr/$screen': typeof AventyrScreenRoute
  '/auth/': typeof AuthIndexRoute
  '/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/seikkailu/': typeof AuthenticatedSeikkailuIndexRoute
  '/opettaja/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRoutesByTo {
  '/adventure': typeof AdventureRouteWithChildren
  '/aventyr': typeof AventyrRouteWithChildren
  '/ga-med-i-gemenskapen': typeof GaMedIGemenskapenRoute
  '/join-community': typeof JoinCommunityRoute
  '/larare': typeof LarareRoute
  '/teacher': typeof TeacherRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/opettaja': typeof AuthenticatedOpettajaRoute
  '/adventure/$screen': typeof AdventureScreenRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/aventyr/$screen': typeof AventyrScreenRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/seikkailu': typeof AuthenticatedSeikkailuIndexRoute
  '/opettaja/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adventure': typeof AdventureRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/aventyr': typeof AventyrRouteWithChildren
  '/ga-med-i-gemenskapen': typeof GaMedIGemenskapenRoute
  '/join-community': typeof JoinCommunityRoute
  '/larare': typeof LarareRoute
  '/teacher': typeof TeacherRoute
  '/_authenticated/seikkailu': typeof AuthenticatedSeikkailuRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/liity-yhteisoon': typeof AuthenticatedLiityYhteisoonRoute
  '/_authenticated/opettaja': typeof AuthenticatedOpettajaRoute
  '/adventure/$screen': typeof AdventureScreenRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/opettaja': typeof AuthOpettajaRoute
  '/auth/student': typeof AuthStudentRoute
  '/aventyr/$screen': typeof AventyrScreenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/seikkailu/$screen': typeof AuthenticatedSeikkailuScreenRoute
  '/_authenticated/seikkailu/': typeof AuthenticatedSeikkailuIndexRoute
  '/_authenticated/opettaja_/oppilas/$userId': typeof AuthenticatedOpettajaOppilasUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/auth'
    | '/aventyr'
    | '/ga-med-i-gemenskapen'
    | '/join-community'
    | '/larare'
    | '/teacher'
    | '/seikkailu'
    | '/admin'
    | '/liity-yhteisoon'
    | '/opettaja'
    | '/adventure/$screen'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/aventyr/$screen'
    | '/auth/'
    | '/seikkailu/$screen'
    | '/seikkailu/'
    | '/opettaja/oppilas/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adventure'
    | '/aventyr'
    | '/ga-med-i-gemenskapen'
    | '/join-community'
    | '/larare'
    | '/teacher'
    | '/admin'
    | '/liity-yhteisoon'
    | '/opettaja'
    | '/adventure/$screen'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/aventyr/$screen'
    | '/'
    | '/auth'
    | '/seikkailu/$screen'
    | '/seikkailu'
    | '/opettaja/oppilas/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/adventure'
    | '/auth'
    | '/aventyr'
    | '/ga-med-i-gemenskapen'
    | '/join-community'
    | '/larare'
    | '/teacher'
    | '/_authenticated/seikkailu'
    | '/_authenticated/admin'
    | '/_authenticated/liity-yhteisoon'
    | '/_authenticated/opettaja'
    | '/adventure/$screen'
    | '/auth/login'
    | '/auth/opettaja'
    | '/auth/student'
    | '/aventyr/$screen'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/seikkailu/$screen'
    | '/_authenticated/seikkailu/'
    | '/_authenticated/opettaja_/oppilas/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdventureRoute: typeof AdventureRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  AventyrRoute: typeof AventyrRouteWithChildren
  GaMedIGemenskapenRoute: typeof GaMedIGemenskapenRoute
  JoinCommunityRoute: typeof JoinCommunityRoute
  LarareRoute: typeof LarareRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/larare': {
      id: '/larare'
      path: '/larare'
      fullPath: '/larare'
      preLoaderRoute: typeof LarareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-community': {
      id: '/join-community'
      path: '/join-community'
      fullPath: '/join-community'
      preLoaderRoute: typeof JoinCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ga-med-i-gemenskapen': {
      id: '/ga-med-i-gemenskapen'
      path: '/ga-med-i-gemenskapen'
      fullPath: '/ga-med-i-gemenskapen'
      preLoaderRoute: typeof GaMedIGemenskapenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aventyr': {
      id: '/aventyr'
      path: '/aventyr'
      fullPath: '/aventyr'
      preLoaderRoute: typeof AventyrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aventyr/$screen': {
      id: '/aventyr/$screen'
      path: '/$screen'
      fullPath: '/aventyr/$screen'
      preLoaderRoute: typeof AventyrScreenRouteImport
      parentRoute: typeof AventyrRoute
    }
    '/auth/student': {
      id: '/auth/student'
      path: '/student'
      fullPath: '/auth/student'
      preLoaderRoute: typeof AuthStudentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/opettaja': {
      id: '/auth/opettaja'
      path: '/opettaja'
      fullPath: '/auth/opettaja'
      preLoaderRoute: typeof AuthOpettajaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/adventure/$screen': {
      id: '/adventure/$screen'
      path: '/$screen'
      fullPath: '/adventure/$screen'
      preLoaderRoute: typeof AdventureScreenRouteImport
      parentRoute: typeof AdventureRoute
    }
    '/_authenticated/opettaja': {
      id: '/_authenticated/opettaja'
      path: '/opettaja'
      fullPath: '/opettaja'
      preLoaderRoute: typeof AuthenticatedOpettajaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liity-yhteisoon': {
      id: '/_authenticated/liity-yhteisoon'
      path: '/liity-yhteisoon'
      fullPath: '/liity-yhteisoon'
      preLoaderRoute: typeof AuthenticatedLiityYhteisoonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seikkailu': {
      id: '/_authenticated/seikkailu'
      path: '/seikkailu'
      fullPath: '/seikkailu'
      preLoaderRoute: typeof AuthenticatedSeikkailuRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seikkailu/': {
      id: '/_authenticated/seikkailu/'
      path: '/'
      fullPath: '/seikkailu/'
      preLoaderRoute: typeof AuthenticatedSeikkailuIndexRouteImport
      parentRoute: typeof AuthenticatedSeikkailuRouteRoute
    }
    '/_authenticated/seikkailu/$screen': {
      id: '/_authenticated/seikkailu/$screen'
      path: '/$screen'
      fullPath: '/seikkailu/$screen'
      preLoaderRoute: typeof AuthenticatedSeikkailuScreenRouteImport
      parentRoute: typeof AuthenticatedSeikkailuRouteRoute
    }
    '/_authenticated/opettaja_/oppilas/$userId': {
      id: '/_authenticated/opettaja_/oppilas/$userId'
      path: '/opettaja/oppilas/$userId'
      fullPath: '/opettaja/oppilas/$userId'
      preLoaderRoute: typeof AuthenticatedOpettajaOppilasUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSeikkailuRouteRouteChildren {
  AuthenticatedSeikkailuScreenRoute: typeof AuthenticatedSeikkailuScreenRoute
  AuthenticatedSeikkailuIndexRoute: typeof AuthenticatedSeikkailuIndexRoute
}

const AuthenticatedSeikkailuRouteRouteChildren: AuthenticatedSeikkailuRouteRouteChildren =
  {
    AuthenticatedSeikkailuScreenRoute: AuthenticatedSeikkailuScreenRoute,
    AuthenticatedSeikkailuIndexRoute: AuthenticatedSeikkailuIndexRoute,
  }

const AuthenticatedSeikkailuRouteRouteWithChildren =
  AuthenticatedSeikkailuRouteRoute._addFileChildren(
    AuthenticatedSeikkailuRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSeikkailuRouteRoute: typeof AuthenticatedSeikkailuRouteRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLiityYhteisoonRoute: typeof AuthenticatedLiityYhteisoonRoute
  AuthenticatedOpettajaRoute: typeof AuthenticatedOpettajaRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOpettajaOppilasUserIdRoute: typeof AuthenticatedOpettajaOppilasUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSeikkailuRouteRoute:
    AuthenticatedSeikkailuRouteRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLiityYhteisoonRoute: AuthenticatedLiityYhteisoonRoute,
  AuthenticatedOpettajaRoute: AuthenticatedOpettajaRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOpettajaOppilasUserIdRoute:
    AuthenticatedOpettajaOppilasUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdventureRouteChildren {
  AdventureScreenRoute: typeof AdventureScreenRoute
}

const AdventureRouteChildren: AdventureRouteChildren = {
  AdventureScreenRoute: AdventureScreenRoute,
}

const AdventureRouteWithChildren = AdventureRoute._addFileChildren(
  AdventureRouteChildren,
)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOpettajaRoute: typeof AuthOpettajaRoute
  AuthStudentRoute: typeof AuthStudentRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthOpettajaRoute: AuthOpettajaRoute,
  AuthStudentRoute: AuthStudentRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AventyrRouteChildren {
  AventyrScreenRoute: typeof AventyrScreenRoute
}

const AventyrRouteChildren: AventyrRouteChildren = {
  AventyrScreenRoute: AventyrScreenRoute,
}

const AventyrRouteWithChildren =
  AventyrRoute._addFileChildren(AventyrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdventureRoute: AdventureRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  AventyrRoute: AventyrRouteWithChildren,
  GaMedIGemenskapenRoute: GaMedIGemenskapenRoute,
  JoinCommunityRoute: JoinCommunityRoute,
  LarareRoute: LarareRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
