/**
 * Human-readable Finnish question labels for every workbook field key.
 * Generated from src/lib/screen-content.tsx so teacher/admin portfolio views
 * can show the actual question instead of the raw database key.
 * Pass values through tr() for FI/SV/EN.
 */
export const FIELD_LABELS: Record<string, string> = {
  "${fieldPrefix}_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "${fieldPrefix}_karkit": "Vahvuudet",
  "${fieldPrefix}_opit": "3. Mitä opit?",
  "${fieldPrefix}_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "${fieldPrefix}_teit": "1. Mitä teit?",
  "screen_10_mina_olen_1": "Minä olen",
  "screen_10_mina_olen_2": "Minä olen",
  "screen_10_mina_olen_3": "Minä olen",
  "screen_10_mina_olen_4": "Minä olen",
  "screen_10_mina_olen_5": "Minä olen",
  "screen_10_mina_olen_6": "Minä olen",
  "screen_10_mina_olen_7": "Minä olen",
  "screen_12_karkkikauppa_picks": "Valitsemasi vahvuuskarkit",
  "screen_13_effect": "Miten omien ydinvahvuuksien hyödyntäminen vaikutti itseesi tai toisiin?",
  "screen_13_examples": "Ajattele itseäsi tekemässä tavanomaisia ja arkisia asioita tai tehtäviä. Miten olet näissä tekemisissä käyttänyt ydinvahvuuksiasi? Kirjoita muutama esimerkki tilanteista.",
  "screen_13_karkki_1": "Vahvuuskarkki…",
  "screen_13_karkki_2": "Vahvuuskarkki…",
  "screen_13_karkki_3": "Vahvuuskarkki…",
  "screen_13_karkki_4": "Vahvuuskarkki…",
  "screen_13_karkki_5": "Vahvuuskarkki…",
  "screen_13_success": "Missä onnistuit omia vahvuuksia hyödyntämällä?",
  "screen_14_tiekartta_1": "Mistä innostut?",
  "screen_14_tiekartta_2": "Minkä tekeminen tuntuu kevyeltä?",
  "screen_14_tiekartta_3": "Mistä luonteenvahvuuksista saat kiitosta ja palautetta toisilta?",
  "screen_14_tiekartta_4": "Mitä rakastat tehdä vapaa-ajalla?",
  "screen_14_tiekartta_5": "Minkä alkamista odotat eniten päivässäsi?",
  "screen_14_tiekartta_6": "Mitä tehdessä aika ja paikka unohtuvat ja pääset flow-tilaan?",
  "screen_14_tiekartta_7": "Mitkä vahvuudet vahvistavat sinua vapaa-ajalla?",
  "screen_14_tiekartta_8": "Mitkä vahvuudet tulevat lukioon, kun sinä tulet paikalle?",
  "screen_14_tiekartta_9": "Mitä vahvuuksia arvostat eniten itsessäsi?",
  "screen_16_kaverisuhteissa": "KAVERISUHTEISSA",
  "screen_16_kotona": "KOTONA",
  "screen_16_koulussa": "KOULUSSA",
  "screen_16_vapaa_ajalla": "VAPAA-AJALLA",
  "screen_17_kasvu": "Miten olet kasvanut ja muuttunut ihmisenä vaikeuksien seurauksena?",
  "screen_17_laheinen": "Mitä sellainen läheinen ihminen, joka tuntee sinut hyvin, kertoisi olevan vahvuuksiasi ja voimavaroja, joiden avulla selviydyt tulevista haasteista?",
  "screen_17_opetukset": "Mitä vaikeudet ovat opettaneet vahvuuksistasi?",
  "screen_18_tunne": "Miltä tämä tuntuisi?",
  "screen_18_vaikutus": "Miten tämä vaikuttaisi arkeesi, entä opintoihin?",
  "screen_20_onnistuminen": "Mieti jotain tilannetta opinnoissa tai vapaa-ajalla, joka sujui hyvin, josta olet ylpeä ja jossa huomasit onnistuvasi sinulle tärkeissä asioissa. Mitä silloin tapahtui? Mikä siinä meni hyvin? Minkälaista palautetta sait toisilta? Mikä siinä oli sinulle tärkeää?",
  "screen_20_tuki": "Mieti onnistumista, jossa pystyit tukemaan ja auttamaan toisia omia vahvuuksiasi hyödyntämällä? Mitä teit ja kenen kanssa olit? Kerro esimerkki.",
  "screen_20_ydinvahvuudet": "Mitä tämä onnistuminen kertoo ydinvahvuuksistasi: mitä omia ydinvahvuuksia käyttämällä onnistuit?",
  "screen_20_yhteinen": "Mitä yhteistä hyvää vahvuutesi edistivät, miten?",
  "screen_21_kehut": "Sain kehuja ja kannustusta seuraavista asioista",
  "screen_21_rohkea": "Olin rohkea kohdatessani tämän uuden haasteen",
  "screen_21_sinnikas": "Olin sinnikäs kun",
  "screen_21_tavoite": "Saavutin tämän tärkeän tavoitteen",
  "screen_21_tunne": "Minusta tuntuu tällä hetkellä tältä, kun muistelen kokemaani",
  "screen_21_uudet": "Löysin itsestäni tilanteessa uusia tai yllättäviä puolia",
  "screen_21_vahvuudet": "Tunnistin nämä vahvuudet jotka mahdollistivat onnistumisen",
  "screen_21_ylpea": "Tästä onnistumisesta olen ylpeä",
  "screen_22_oppi": "Mieti jotain tilannetta, jossa et onnistunut hyödyntämään vahvuuksiasi, tai käytit niitä liikaa? Mitä tämä tilanne opetti sinulle?",
  "screen_22_tulevaisuus": "Mieti jotain tilannetta opinnoissa tai vapaa-ajalla, jossa voit lähitulevaisuudessa hyödyntää vahvuuksiasi? Mikä tulee menemään hyvin? Mistä voit huomata, että olet hyödyntänyt vahvuuksiasi tietoisemmin?",
  "screen_23_pair_1": "Mistä innostut?",
  "screen_23_pair_10": "Mitä luonteenvahvuuksia hyödynnät eniten vapaalla?",
  "screen_23_pair_2": "Minkä tekeminen tuntuu kevyeltä?",
  "screen_23_pair_3": "Mistä luonteenvahvuuksista saat kiitosta ja palautetta toisilta?",
  "screen_23_pair_4": "Mikä on parasta opinnoissa?",
  "screen_23_pair_5": "Mitkä asiat päätyvät love-to-do -listalle?",
  "screen_23_pair_6": "Mitä tehdessä aika ja paikka unohtuvat ja pääset flow-tilaan?",
  "screen_23_pair_7": "Mitkä vahvuudet tulevat lukioon, kun sinä tulet paikalle?",
  "screen_23_pair_8": "Mitä vahvuuksia arvostat eniten itsessäsi?",
  "screen_23_pair_9": "Mitä samoja vahvuuksia sinussa oli jo lapsena?",
  "screen_24_palaute_1": "Sinun vahvuuksiasi ovat ainakin…",
  "screen_24_palaute_2": "Tämä oli tärkeää kuulla, koska…",
  "screen_24_palaute_3": "WAU, OPIN ETTÄ…",
  "screen_25_tassa_1": "Minulle tärkeää on",
  "screen_25_tassa_10": "Lukiossa haluaisin oppia",
  "screen_25_tassa_11": "Lukiossa minua innostaa",
  "screen_25_tassa_2": "Tulen iloiseksi, kun",
  "screen_25_tassa_3": "Läheisissäni parasta on",
  "screen_25_tassa_4": "Osaan hyvin ja tykkään tehdä",
  "screen_25_tassa_5": "Parasta ryhmässäni on",
  "screen_25_tassa_6": "Opinnoissa lempiaineita ovat",
  "screen_25_tassa_7": "Minulle on vaikeaa",
  "screen_25_tassa_8": "Lempitekemistä",
  "screen_25_tassa_9": "Vapaa-ajalla tykkään",
  "screen_26_likert_1": "Pystyn yleensä tekemään sitä, mitä teen parhaiten",
  "screen_26_likert_10": "Vahvuuksien käyttäminen tekemissäni asioissa on minusta helppoa",
  "screen_26_likert_11": "Pystyn käyttämään vahvuuksiani monissa eri tilanteissa",
  "screen_26_likert_12": "Suurimman osan ajastani teen asioita, joissa olen hyvä",
  "screen_26_likert_13": "Vahvuuksien käyttäminen on minulle tuttua",
  "screen_26_likert_14": "Pystyn käyttämään vahvuuksiani monin eri tavoin",
  "screen_26_likert_2": "Hyödynnän aina vahvuuksiani",
  "screen_26_likert_3": "Pyrin aina käyttämään vahvuuksiani",
  "screen_26_likert_4": "Saavutan haluamani käyttämällä vahvuuksiani",
  "screen_26_likert_5": "Käytän vahvuuksiani päivittäin",
  "screen_26_likert_6": "Käytän vahvuuksiani saadakseni elämässä sen, mitä haluan",
  "screen_26_likert_7": "Opinnoissani minulla on paljon mahdollisuuksia käyttää vahvuuksiani",
  "screen_26_likert_8": "Elämä tarjoilee minulle monia eri tapoja käyttää vahvuuksiani",
  "screen_26_likert_9": "Vahvuuksien käyttäminen on minulle luontaista",
  "screen_29_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "screen_29_karkit": "Vahvuudet",
  "screen_29_opit": "3. Mitä opit?",
  "screen_29_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "screen_29_teit": "1. Mitä teit?",
  "screen_30_kiinnostukset": "Mitä harrastat? Mitkä ovat innostuksen ja intohimon kohteita vapaa-ajallasi?",
  "screen_30_lahjakkuudet": "Missä olet hyvä?",
  "screen_30_resurssit": "Mitkä asiat tai henkilöt ovat voimavarojasi? Mikä auttaa sinua pysymään vahvana vaikeina aikoina? Mikä tuo elämääsi merkitystä?",
  "screen_30_taidot": "Mitä taitoja sinulla jo on, joita hyödynnät opinnoissa?",
  "screen_31_tiekartta_1": "Keneltä saan tukea ja opastusta?",
  "screen_31_tiekartta_2": "Mitä vahvuuksiani voin hyödyntää?",
  "screen_31_tiekartta_3": "Mitä minun kannattaisi vielä oppia?",
  "screen_31_tiekartta_4": "Mitä jo osaan hyvin?",
  "screen_31_tiekartta_5": "Unelmieni ammatti",
  "screen_32_minaopisk_1": "Mikä saa sinut innostumaan opinnoissa?",
  "screen_32_minaopisk_2": "Minkä tekemiseen uppoudut?",
  "screen_32_minaopisk_3": "Minkä parissa jaksat olla sinnikäs ja ylittää esteitä?",
  "screen_32_minaopisk_4": "Mistä olet saanut kannustavaa palautetta opettajilta tai opiskelutovereilta?",
  "screen_32_minaopisk_5": "Mistä olet erityisen kiinnostunut opinnoissa?",
  "screen_32_minaopisk_6": "Mitä vahvuuksia tavallisesti hyödynnät opintojen aikana?",
  "screen_33_erityistaito_1": "Erityistaito…",
  "screen_33_erityistaito_10": "Erityistaito…",
  "screen_33_erityistaito_2": "Erityistaito…",
  "screen_33_erityistaito_3": "Erityistaito…",
  "screen_33_erityistaito_4": "Erityistaito…",
  "screen_33_erityistaito_5": "Erityistaito…",
  "screen_33_erityistaito_6": "Erityistaito…",
  "screen_33_erityistaito_7": "Erityistaito…",
  "screen_33_erityistaito_8": "Erityistaito…",
  "screen_33_erityistaito_9": "Erityistaito…",
  "screen_34_aiheet": "Mistä tykkäsit koulussa ala-asteella, entä yläasteella?",
  "screen_34_onnistuminen": "Mikä onnistuminen sinulle on jäänyt mieleen peruskoulusta?",
  "screen_34_oppi": "Minkälaisia asioita opit nopeasti ja helposti?",
  "screen_34_palaute": "Mistä sait rohkaisevaa palautetta peruskoulussa opettajilta entä luokkakavereilta?",
  "screen_36_hyodynnan": "3. Miten hyödynnän vahvuuksia",
  "screen_36_taidot": "4. Mitä muita taitoja tarvitsen",
  "screen_36_tavoite": "1. Tavoitteeni ja miksi se on minulle tärkeä",
  "screen_36_vahvuudet": "2. Vaaditut vahvuudet",
  "screen_37_arvostan": "Mukavia asioita — Arvostan itsessäni",
  "screen_37_paikkoja": "Paikkoja — Näissä paikoissa viihdyn ja pääsen käyttämään vahvuuksiani",
  "screen_37_vahvuuksiani": "Omia vahvuuksia — Vahvuuksiani ovat mielestäni",
  "screen_38_muistetaan": "Millaisista asioista minut muistetaan / tunnistetaan parhaiten?",
  "screen_38_tarkeaa": "Mikä palautteessa on minulle tärkeää?",
  "screen_38_uutta": "Mitä uutta opin palautteista?",
  "screen_38_yhteisoon": "Mitä hyvää vahvuuteni tuovat yhteisööni?",
  "screen_39_mina_olen_1": "Minä olen",
  "screen_39_mina_olen_2": "Minä olen",
  "screen_39_mina_olen_3": "Minä olen",
  "screen_39_mina_olen_4": "Minä olen",
  "screen_39_mina_olen_5": "Minä olen",
  "screen_39_mina_olen_6": "Minä olen",
  "screen_39_mina_olen_7": "Minä olen",
  "screen_41_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "screen_41_karkit": "Vahvuudet",
  "screen_41_opit": "3. Mitä opit?",
  "screen_41_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "screen_41_teit": "1. Mitä teit?",
  "screen_42_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "screen_42_karkit": "Vahvuudet",
  "screen_42_opit": "3. Mitä opit?",
  "screen_42_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "screen_42_teit": "1. Mitä teit?",
  "screen_43_kiitollinen": "Mistä olet kiitollinen perheessäsi?",
  "screen_43_parasta": "Mikä on parasta perheessäsi? Miten erilaiset vahvuudet näkyvät perheessänne?",
  "screen_43_vahvuudet": "Minkälaisia vahvuuksia sinulla on perheenjäsenenä? Miten ne näkyvät?",
  "screen_43_yhdessa": "Mitä tykkäätte tehdä yhdessä?",
  "screen_44_perheenjasenena": "Kirjoita itsellesi muistiin, millainen olet perheenjäsenenä ja millaisia vahvuuksia tuot perheeseesi.",
  "screen_45_vanhemmat_1": "Millainen lapsi olin?",
  "screen_45_vanhemmat_2": "Mitkä olivat lempileikkejäni?",
  "screen_45_vanhemmat_3": "Mistä innostuin?",
  "screen_45_vanhemmat_4": "Missä olin lapsena hyvä?",
  "screen_45_vanhemmat_5": "Mistä sain kannustusta ja kehuja?",
  "screen_45_vanhemmat_6": "Mitä vahvuuksia minussa huomattiin jo lapsena?",
  "screen_45_vanhemmat_7": "Mitä toivoit minusta tulevan?",
  "screen_45_vanhemmat_8": "Mitä haluat vielä sanoa minulle vahvuuksistani?",
  "screen_48_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "screen_48_karkit": "Vahvuudet",
  "screen_48_opit": "3. Mitä opit?",
  "screen_48_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "screen_48_teit": "1. Mitä teit?",
  "screen_49_enemman": "Mitä vahvuuksiasi haluaisit hyödyntää enemmän vapaa-ajallasi?",
  "screen_49_harrastukset": "Mitä harrastuksia sinulla on?",
  "screen_49_tykkaat": "Mitä tykkäät tehdä vapaa-ajalla?",
  "screen_49_vahvuudet": "Mitä vahvuuksia tunnistat itsessäsi vapaa-ajalla ja harrastuksissa?",
  "screen_5_first_impression": "Mikä tästä jäi mieleen? (vapaaehtoinen)",
  "screen_51_love_1": "Asia, jota rakastan tehdä…",
  "screen_51_love_2": "Asia, jota rakastan tehdä…",
  "screen_51_love_3": "Asia, jota rakastan tehdä…",
  "screen_51_love_4": "Asia, jota rakastan tehdä…",
  "screen_51_love_5": "Asia, jota rakastan tehdä…",
  "screen_52_konkreettisesti": "Kuvittele, että voisit tehdä eniten rakastamaasi asiaa enemmän — miltä se konkreettisesti tuntuisi? Mihin haluaisit käyttää enemmän aikaa?",
  "screen_52_vahvuudet": "Kirjoita mitä vahvuuksiasi hyödynnät tehdessäsi rakastamiasi asioita vapaa-ajalla!",
  "screen_54_kehittaneet": "Mitä vahvuuksia kiinnostuksen kohteeni ovat kehittäneet?",
  "screen_54_uudet": "Mitä uusia taitoja olet oppinut kiinnostuksen kohteiden parissa?",
  "screen_54_valitsin": "Mitä valitsin",
  "screen_56_hyodynnat": "4. Miten hyödynnät oppimaasi?",
  "screen_56_karkit": "Vahvuudet",
  "screen_56_opit": "3. Mitä opit?",
  "screen_56_seuraavaksi": "2. Mitä tapahtui seuraavaksi?",
  "screen_56_teit": "1. Mitä teit?",
  "screen_57_parasta": "Parasta ystävissäni on",
  "screen_57_ystavien": "Ystävieni mielestä vahvuuksiani ovat",
  "screen_58_muistavat": "Millaisista asioista ystäväni muistavat minut parhaiten?",
  "screen_58_parasta": "Mikä on parasta ystävissäni?",
  "screen_58_tarkeaa": "Mikä palautteessa on minulle tärkeää?",
  "screen_58_uutta": "Mitä uutta opin palautteista?",
  "screen_6_known_strengths": "Valitse ne vahvuudet, jotka tunnistat itsessäsi tai läheisissäsi. Voit palata muokkaamaan valintaasi myöhemmin.",
  "screen_60_koulusta": "Koulusta",
  "screen_60_perheelta": "Perheeltä",
  "screen_60_vapaa_ajalta": "Vapaa-ajalta",
  "screen_60_ystavilta": "Ystäviltä",
  "screen_61_eroavat": "Miten ne eroavat?",
  "screen_61_huomataan": "Mitä vahvuuksia sinussa huomataan?",
  "screen_61_muistaa": "Mitä haluat muistaa palautteista?",
  "screen_61_samaa": "Mitä samaa niissä on?",
  "screen_61_yllatti": "Mikä palautteissa yllätti?",
  "screen_62_visioni_1": "Millainen ihminen haluat olla?",
  "screen_62_visioni_2": "Mitä vahvuuksia ja taitoja haluaisit kehittää itsessäsi ja miksi?",
  "screen_62_visioni_3": "Onko sinulla joku esikuva, jolla on näitä ominaisuuksia? Kuka ja mitä?",
  "screen_62_visioni_4": "Miten voit kompensoida omia heikkouksiasi vahvuuksiesi avulla?",
  "screen_62_visioni_5": "Mitä toivoisit, että ystäväsi ja perheesi kertoisivat sinusta, kun et ole paikalla? Millaisena haluat tulla muistetuksi?",
  "screen_63_kerro_1": "Mitkä ovat ydinvahvuuksiasi? Mitä rakastat tehdä? Milloin olet aidoimmillasi? Mistä saat energiaa? Mitkä vahvuuksia voisit nostaa esiin videolla entä työhaastattelussa?",
  "screen_63_kerro_2": "Missä ammateissa tai työtehtävissä vahvuutesi pääsisivät oikeuksiinsa?",
  "screen_63_kerro_3": "Miten hyödynnät vahvuuksiasi eri ihmisten kanssa?",
  "screen_63_kerro_4": "Missä ympäristöissä vahvuutesi pääsevät esiin parhaiten?",
  "screen_63_kerro_5": "Mistä saat usein positiivista palautetta toisilta?",
  "screen_63_kerro_6": "Miten käytät vahvuuksiasi ryhmässä? Mihin se vaikuttaa?",
  "screen_63_kerro_7": "Mitä haluat sanoa videolla tai esityksessä? Mitä haluat jättää katsojan mieleen?",
  "screen_64_havainnot": "Omat havainnot vahvuuksistani…",
  "screen_64_muistaa": "Tämän haluan muistaa ainakin…",
  "screen_64_tarkeaa": "Minulle on tärkeää…",
  "screen_65_notes": "Vapaita muistiinpanoja",
  "screen_66_notes": "Vapaita muistiinpanoja",
  "screen_69_kehittamisesta": "Minkä vahvuuksien kehittämisestä olisi sinulle eniten iloa?",
  "screen_69_kertovat": "Mitä vahvuutesi kertovat sinusta?",
  "screen_69_tilanteissa": "Missä tilanteissa ja ympäristöissä pääset käyttämään vahvuuksiasi päivittäin?",
  "screen_69_toimia": "Miten sinun kannattaisi toimia, jos haluaisit hyödyntää vahvuuksiasi enemmän — opinnoissa, vapaa-ajalla ja ystävyyssuhteissa?",
  "screen_8_s8_authentic": "Milloin koet olevasi aidoimmillasi ja onnistut sinulle tärkeissä asioissa?",
  "screen_8_s8_freetime": "Mitkä ovat kiinnostuksen kohteesi vapaa-ajalla?",
  "screen_8_s8_love": "Tiedätkö, mitä rakastat tehdä?",
  "screen_8_s8_motivate": "Minkä alkamista odotat? Mistä koulutehtävistä motivoidut eniten?",
  "screen_8_s8_persist": "Mitä tehdessä jaksat ponnistella sinnikkäästi ja ylittää haasteita?",
  "screen_9_best_sides": "Parhaita puoliani ovat:",
  "screen_9_learned": "Olen oppinut sinulta seuraavia asioita:",
  "screen_9_spotted": "Olen bongannut niitä erityisesti kun:",
  "screen_9_strengths": "Vahvuuksiani ovat mielestäni:",
};

export function fieldLabel(key: string): string | null {
  return FIELD_LABELS[key] ?? null;
}
